### ISSUE TITLE
Failed to activate the browser-plus package

### ISSUE THREAD

**Issue by braver** [skandasoft/browser-plus#7] opened 2015-05-21 19:09 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.200.0
**System**: Mac OS X 10.10.4
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.22

### Stack Trace

Failed to activate the browser-plus package

```
At ENOENT: no such file or directory, open '/Users/koen/.atom/dev/packages/browser-plus/resources/browser-plus-client.js'

Error: ENOENT: no such file or directory, open '/Users/koen/.atom/dev/packages/browser-plus/resources/browser-plus-client.js'
    at Error (native)
    at Object.fs.openSync (fs.js:544:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
    at Object.fs.readFileSync (fs.js:396:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at Object.module.exports.BrowserPlus.activate (/Users/koen/.atom/packages/browser-plus/lib/browser-plus.coffee:37:20)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "open-on-github",
      "deprecation-cop",
      "terminal-panel"
    ],
    "themes": [
      "isotope-ui",
      "duotone-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
browser-plus, v0.0.22
color-picker, v1.7.0
duotone-light-syntax, v0.2.0
isotope-ui, v2.1.5
jslint, v1.3.3
language-alan, v0.0.0
minimap, v4.9.0
typewriter, v0.3.3

# Dev
No dev packages
```

**Comment by skandasoft** [comment] 2015-05-21 21:01
surprised as to why file doesn't exist? is that the packages path/  you installed in a different directory

**Comment by braver** [comment] 2015-05-22 06:47
I just clicked the install button in atom.

**Comment by skandasoft** [comment] 2015-05-22 14:16
May be because of permission issues..I didn't see any body reporting it.. I will leave it open to see if anybody else has the problem..Please try installing the latest and let me know it it works.

**Comment by skandasoft** [comment] 2015-06-01 22:55
I am not seeing anybody reportng installation issue...please feel free to reopen assuming the latest patch fixed it..

**Comment by sononix** [comment] 2015-06-03 07:59
snap! - installed browser plus and couldnt figure out why it wasnt appearing in my tabs - this morning getting the same jquery message - the plugin has never worked for me 
mac 10.3

installed package
Hydrogen		haskell-ghc-mod		linter-hlint
haskell-grammar		linter-rust
atom-justify		helium			livereload
autocomplete-elixir	ide-haskell		node-debugger
autocomplete-haskell	iex			racer
browser-plus		javascript-snippets	react
build			language-elixir		react-snippets
elixir-cmd		language-haskell	rust-api-docs-helper
gulp-control		language-julia		turbo-javascript
gulp-helper		language-rust		unitjs
gulp-snippets		linter-elixirc

**Comment by skandasoft** [comment] 2015-06-03 11:28
What  do you mean by the tab never appeared.  You use the cmd browser-plus:open.

What is about the jquery msg

**Comment by jekriske** [comment] 2015-06-05 22:30
Same issue here... Installed latest update, package crashed
ENOENT: no such file or directory, open '/Users/jeff/.atom/packages/browser-plus/resources/jquery-1.11.3.js'

it looks like you included jquery-1.11.3.min.js and you're trying to call the full jquery package... it's a common mistake.

**Comment by bakki** [comment] 2015-06-09 19:32
Just upgraded to 0.0.23 which complains that
ENOENT: no such file or directory, open '/Users/bakki/.atom/packages/browser-plus/resources/jquery-1.11.3.js'
The resources directory has jquery-1.11.3.min.js instead.
I downloaded & copied jquery-1.11.3.js into the resources directory, 'disable' and 'enable' the package and it seems to have fixed the issue.

**Comment by larpo1** [comment] 2016-05-24 14:17
I have this issue too: 

ENOENT: no such file or directory, open '/Users/larpo/.atom/packages/browser-plus/resources/browser-plus-client.js'
Hide Stack Trace
Error: ENOENT: no such file or directory, open '/Users/larpo/.atom/packages/browser-plus/resources/browser-plus-client.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at Object.module.exports.BrowserPlus.activate (/Users/larpo/.atom/packages/browser-plus/lib/browser-plus.coffee:66:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:328:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by ninthart** [comment] 2016-07-05 07:12
Yep, I've got it too:

[Enter steps to reproduce below:]

1. Install Browser-Plus package from Atom
2. That's it.

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.63


### Stack Trace

Failed to activate the browser-plus package

```
At ENOENT: no such file or directory, open '/Users/bradbrooks/.atom/packages/browser-plus/resources/browser-plus-client.js'

Error: ENOENT: no such file or directory, open '/Users/bradbrooks/.atom/packages/browser-plus/resources/browser-plus-client.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at Object.module.exports.BrowserPlus.activate (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus.coffee:43:7)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:342:19
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:631:20
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Config.module.exports.Config.emitChangeEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:816:29)
    at Config.module.exports.Config.setRawValue (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:608:19)
    at Config.module.exports.Config.set (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:227:14)
    at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/config.js:377:12)
    at Package.module.exports.Package.enable (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:77:26)
    at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:169:14)
    at HTMLButtonElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:324:27)
    at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by skandasoft** [comment] 2016-07-05 13:10
can you check the latest patch

**Comment by ninthart** [comment] 2016-07-05 13:18
OK, I installed the update, and everything seemed to work (i.e. it activated) until I tried to open a preview of a HTML file. Then it threw the following error:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.64


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:833:27)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```

### Commands

```
     -0:34.4.0 command-palette:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:31.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:30.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:30.6.0 browser-plus:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

**Comment by skandasoft** [comment] 2016-07-05 13:34
can you uninstall and reinstall..otherwise go to the package directory for browser plus and in command prompt type npm install ( you don't have all the dependencies - "jquery-ui": "^1.10.5" )

**Comment by ninthart** [comment] 2016-07-05 13:46
OK, I did as you asked, and uninstalled the package and then reinstalled it. On activation, it threw the following error:

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.64


### Stack Trace

Failed to activate the browser-plus package

```
At ENOENT: no such file or directory, open '/Users/bradbrooks/.atom/packages/browser-plus/resources/browser-plus-client.js'

Error: ENOENT: no such file or directory, open '/Users/bradbrooks/.atom/packages/browser-plus/resources/browser-plus-client.js'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:158:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
    at Object.module.exports.BrowserPlus.activate (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus.coffee:43:7)
    at Package.module.exports.Package.activateNow (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:183:20)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:538:21)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
    at exit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:222:18
    at Socket.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:95:20)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:477:12)
```

### Commands

```
     -0:29.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:27.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

So then I uninstalled again, installed the package via command line (apm install), cd' to the package directory and ran npm install.

Then after closing and reopening Atom, I tried to preview a html file and got the following error again:


**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.64


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:833:27)
    at Immediate._onImmediate (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:664:33)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

### Commands

```
     -0:11.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.0 browser-plus:open (atom-text-editor.editor)
```

**Comment by skandasoft** [comment] 2016-07-05 17:03
can you check the latest patch

**Comment by ninthart** [comment] 2016-07-05 17:16
OK, I uninstalled and reinstalled the updated version, I checked that the dependencies were all in place, and then I tested against a html file. Still the same basic error was thrown:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Mac OS X 10.11.5
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.64


### Stack Trace

Uncaught TypeError: jQ(...).autocomplete is not a function

```
At /Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98

TypeError: jQ(...).autocomplete is not a function
    at BrowserPlusView.module.exports.BrowserPlusView.initialize (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:98:16)
    at BrowserPlusView.View [as constructor] (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at new BrowserPlusView (/Users/bradbrooks/.atom/packages/browser-plus/lib/browser-plus-view.coffee:23:5)
    at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:136:16)
    at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/view-registry.js:86:21)
    at atom-pane.PaneElement.getActiveView (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:194:25)
    at atom-pane.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:51:55)
    at atom-pane.PaneElement.activated (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.activate (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/pane.js:833:27)
    at Immediate._onImmediate (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/tabs/lib/tab-bar-view.js:664:33)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by skandasoft** [comment] 2016-07-05 23:08
another patch..

**Comment by ninthart** [comment] 2016-07-06 07:57
That sorted it! I'm pleased to say that everything is working well again, thank you!

**Closed** 2016-08-03 10:54 UTC

**Comment by Timemashine** [comment] 2016-11-29 21:39
## I hope it's my fault. Otherewise... another patch?

I was looking for some new Packages and installed a lot to check them out.
Its probable that some of these Packages coursed this Error.

I have Installed the following Packages, Atom has crashed and after relaunch the Message Appeared.

```coffee
expose, v0.12.2 (inactive)
remote-edit2, v3.0.0 (inactive)
term, v0.2.4 (inactive)
term3, v0.22.1 (inactive)
atom-terminal-panel, v4.4.4 (inactive)
```

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12.1
**Thrown From**: [browser-plus](https://github.com/skandasoft/browser-plus) package, v0.0.86

### Stack Trace

Failed to activate the browser-plus package

```
At Cannot read property 'get' of undefined

TypeError: Cannot read property 'get' of undefined
    at Object.activate (/Users/andre/.atom/packages/browser-plus/lib/browser-plus.coffee:38:64)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:157:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:150:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:548:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:529:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:524:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:506:46)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "disabledPackages": [
      "tool-bar-main",
      "php-debug",
      "project-view",
      "project-environment",
      "native-color-picker",
      "preview-plus",
      "php-refactoring",
      "php-cs-fixer",
      "minimap",
      "project-manager",
      "Remote-FTP",
      "opened-files",
      "linter-markdown",
      "remote-edit2",
      "activate-power-mode",
      "markdown-folder",
      "tidy-tabs",
      "an-color-picker",
      "atom-spotified",
      "package-settings"
    ],
    "ignoredNames": [
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "symbols-list",
      "atom-spotified"
    ],
    "projectHome": "/Users/andre/Developer/Atom/Packages",
    "telemetryConsent": "no",
    "themes": [
      "nucleus-dark-ui",
      "monokai-fresh-syntax"
    ]
  },
  "browser-plus": {
    "homepage": "http://tochelet.andrekliewer.de/?debug",
    "live": 1000
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0 (inactive)
advanced-open-file, v0.16.4 (inactive)
an-color-picker, v1.0.2 (inactive)
atom-hide-tabs, v0.2.1 (inactive)
bottom-dock, v0.4.4 (inactive)
browse, v1.3.2 (inactive)
browser-plus, v0.0.86 (inactive)
chrome-color-picker, v0.8.0 (inactive)
clipboard-plus, v0.5.1 (inactive)
diff-pane, v0.1.0 (inactive)
docblockr, v0.8.7 (inactive)
expose, v0.12.2 (inactive)
file-icons, v1.7.25 (inactive)
fold-lines, v0.2.1 (inactive)
genesis-ui, v0.5.0 (inactive)
git-plus, v5.25.5 (inactive)
git-time-machine, v1.5.4 (inactive)
hyperclick-php, v0.2.1 (inactive)
language-csv, v1.1.2 (inactive)
language-htaccess, v0.1.1 (inactive)
linter, v1.11.18 (inactive)
linter-markdown, v3.0.2 (inactive)
linter-php, v1.3.1 (inactive)
linter-sass-lint, v1.7.4 (inactive)
linter-tidy, v2.3.0 (inactive)
log-view, v0.0.0 (inactive)
lucid-tabs, v1.1.1 (inactive)
man, v0.5.0 (inactive)
markdown-folder, v0.5.0 (inactive)
markdown-mindmap, v0.2.4 (inactive)
markdown-preview-plus, v2.4.0 (inactive)
minimap, v4.25.6 (inactive)
monokai-fresh-syntax, v0.0.2 (inactive)
native-color-picker, v0.2.0 (inactive)
native-ui, v0.19.1 (inactive)
nucleus-dark-ui, v0.10.18 (inactive)
open-in-developer-mode, v0.1.0 (inactive)
opened-files, v0.3.6 (inactive)
outline-selection, v0.3.0 (inactive)
package-developer-toolbar, v0.8.0 (inactive)
package-list, v0.1.2 (inactive)
package-settings, v1.1.0 (inactive)
php-cs-fixer, v3.0.0 (inactive)
php-debug, v0.2.3 (inactive)
php-integrator-annotations, v1.0.3 (inactive)
php-integrator-autocomplete-plus, v1.1.5 (inactive)
php-integrator-base, v1.2.6 (inactive)
php-integrator-call-tips, v1.1.1 (inactive)
php-integrator-linter, v1.2.1 (inactive)
php-integrator-navigation, v1.0.3 (inactive)
php-integrator-refactoring, v1.1.1 (inactive)
php-integrator-symbol-viewer, v0.6.4 (inactive)
php-integrator-tooltips, v1.0.4 (inactive)
php-refactoring, v1.4.0 (inactive)
preview-plus, v1.2.7 (inactive)
project-environment, v1.0.4 (inactive)
project-manager, v3.3.3 (inactive)
project-plus, v0.9.0 (inactive)
project-sidebar, v1.3.0 (inactive)
project-view, v0.6.1 (inactive)
Remote-FTP, v0.9.4 (inactive)
save-autorun, v0.3.3 (inactive)
seti-ui, v1.3.2 (inactive)
symbols-list, v2.3.1 (inactive)
tablr, v1.5.5 (inactive)
term, v0.2.4 (inactive)
term3, v0.22.1 (inactive)
tidy-tabs, v0.3.0 (inactive)
tool-bar, v1.0.1 (inactive)
tool-bar-basic, v1.2.0 (inactive)
tool-bar-main, v0.0.10 (inactive)
tree-view-git-status, v1.2.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (inactive)
archive-view, v0.62.0 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.13.1 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.4 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.42.0 (inactive)
bracket-matcher, v0.82.2 (inactive)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.40.0 (inactive)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (inactive)
image-view, v0.60.0 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (inactive)
metrics, v1.1.2 (inactive)
notifications, v0.65.1 (inactive)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (inactive)
snippets, v1.0.4 (inactive)
spell-check, v0.68.4 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.2 (inactive)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.210.0 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.35.1 (inactive)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.38.2 (inactive)
language-c, v0.54.0 (inactive)
language-clojure, v0.22.1 (inactive)
language-coffee-script, v0.48.0 (inactive)
language-csharp, v0.13.0 (inactive)
language-css, v0.40.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.43.0 (inactive)
language-html, v0.47.1 (inactive)
language-hyperlink, v0.16.1 (inactive)
language-java, v0.24.0 (inactive)
language-javascript, v0.122.0 (inactive)
language-json, v0.18.3 (inactive)
language-less, v0.29.6 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.1 (inactive)
language-ruby, v0.70.2 (inactive)
language-ruby-on-rails, v0.25.1 (inactive)
language-sass, v0.57.0 (inactive)
language-shellscript, v0.23.0 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.25.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.29.1 (inactive)
language-toml, v0.18.1 (inactive)
language-xml, v0.34.12 (inactive)
language-yaml, v0.27.1 (inactive)
